on:
  push:
    branches:
      - master
jobs:
  updateGraphs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Generate graphs
        run: python ml_1.py

      - name: Update graphs
        run: |
          git config --global user.name 'okaheel'
          git config --global user.email 'omar.kaheel@ucolorado.com'
          git commit -m "Update graphs"
          git push
